export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const VisibilityFilters = {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_COMPLETED: 'SHOW_COMPLETED',
	SHOW_ACTIVE: 'SHOW_ACTIVE'
};


export const OPEN_MAKE_ORDER_FORM = 'OPEN_MAKE_ORDER_FORM';
export const CLOSE_MAKE_ORDER_FORM = 'CLOSE_MAKE_ORDER_FORM';
export const MAKE_ORDER = 'MAKE_ORDER';