# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('advice_text', models.TextField(max_length=8172, verbose_name='Содержимое совета')),
            ],
            options={
                'verbose_name': 'Совет',
                'verbose_name_plural': 'Советы',
            },
        ),
        migrations.CreateModel(
            name='Ensure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensure_name', models.CharField(max_length=300, verbose_name='Срок гарантии')),
            ],
            options={
                'verbose_name': 'Гарантия',
                'verbose_name_plural': 'Гарантии',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=200, verbose_name='Название варианта услуги')),
            ],
            options={
                'verbose_name': 'Вариант прдоставляемой услуги',
                'verbose_name_plural': 'Варианты предоставляемых услуг',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('service_description', models.TextField(max_length=8172, verbose_name='Описание услуги')),
                ('options', models.ManyToManyField(to='present.Option', verbose_name='Варианты услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=200, verbose_name='Название площади')),
                ('price', models.IntegerField(verbose_name='Цена обработки')),
                ('ensure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='present.Ensure', verbose_name='Название площади')),
            ],
            options={
                'verbose_name': 'Площадь',
                'verbose_name_plural': 'Площади',
            },
        ),
        migrations.AddField(
            model_name='option',
            name='spaces',
            field=models.ManyToManyField(to='present.Space', verbose_name='Помещения'),
        ),
    ]
